---
# Source: flux/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  labels:
    app: flux
    chart: flux-1.3.0
    release: flux
    heritage: Helm
---
# Source: flux/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: flux-git-deploy
type: Opaque
---
# Source: flux/templates/kube.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-kube-config
data:
  config: |
    apiVersion: v1
    clusters: []
    contexts:
    - context:
        cluster: ""
        namespace: default
        user: ""
      name: default
    current-context: default
    kind: Config
    preferences: {}
    users: []
---
# Source: flux/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: flux
  labels:
    app: flux
    chart: flux-1.3.0
    release: flux
    heritage: Helm
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
# Source: flux/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: flux
  labels:
    app: flux
    chart: flux-1.3.0
    release: flux
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux
subjects:
  - name: flux
    namespace: "flux"
    kind: ServiceAccount
---
# Source: flux/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flux
  labels:
    app: flux
    chart: flux-1.3.0
    release: flux
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 3030
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: flux
    release: flux
---
# Source: flux/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  labels:
    app: flux
    chart: flux-1.3.0
    release: flux
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux
      release: flux
  template:
    metadata:
      annotations:
      labels:
        app: flux
        release: flux
    spec:
      serviceAccountName: flux
      volumes:
      - name: kubedir
        configMap:
          name: flux-kube-config
      - name: git-key
        secret:
          secretName: flux-git-deploy
          defaultMode: 0400
      - name: git-keygen
        emptyDir:
          medium: Memory
      containers:
        - name: flux
          image: "docker.io/fluxcd/flux:1.19.0"
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 3030
            protocol: TCP
          livenessProbe:
            httpGet:
              port: 3030
              path: /api/flux/v6/identity.pub
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 3030
              path: /api/flux/v6/identity.pub
            initialDelaySeconds: 5
            timeoutSeconds: 5
          volumeMounts:
          - name: kubedir
            mountPath: /root/.kubectl
          - name: git-key
            mountPath: /etc/fluxd/ssh
            readOnly: true
          - name: git-keygen
            mountPath: /var/fluxd/keygen
          env:
          - name: KUBECONFIG
            value: /root/.kubectl/config
          envFrom:
          - secretRef:
              name: flux-git
          args:
          - --log-format=fmt

          - --ssh-keygen-dir=/var/fluxd/keygen
          - --ssh-keygen-format=RFC4716
          - --k8s-secret-name=flux-git-deploy
          - --memcached-hostname=flux-memcached
          - --sync-state=git
          - --memcached-service=
          - --git-url=$(GIT_URL)
          - --git-branch=main
          - --git-path=$(GIT_PATH)
          - --git-readonly=true
          - --git-user=Weave Flux
          - --git-email=support@weave.works
          - --git-verify-signatures=false
          - --git-set-author=false
          - --git-poll-interval=10s
          - --git-timeout=20s
          - --sync-interval=5m
          - --git-ci-skip=false
          - --automation-interval=5m
          - --registry-rps=200
          - --registry-burst=125
          - --registry-trace=false
          - --registry-disable-scanning
          - --sync-garbage-collection=true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
      nodeSelector:
        beta.kubernetes.io/os: linux
